### ISSUE TITLE
Missing icp_without_cov

### ISSUE THREAD

**Issue by ignaciotb** [CAOR-MINES-ParisTech/3d-icp-cov#1]
Hi, 
I've installed and managed to run your main.py but it seems to be missing an executable called icp_without_cov within the examples folder from libpointmatcher.  
Have I missed something? 
Thanks

**Comment by mbrossar** [comment]
Hi,
The compilation of icp_without_cov was not done.
You could edit our fork or libpointmatcher and edit examples/CMakeLists.txt as [follow](https://github.com/CAOR-MINES-ParisTech/libpointmatcher/blob/master/examples/CMakeLists.txt)

**Comment by ignaciotb** [comment]
Hi, 
Thanks for the quick reply. 
Now the compilation fails with 
```
error: too many arguments to function call, expected 0, have 2
        icp.errorMinimizer->getCovariance(censi_cov, bonnabel_cov);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
/home/torroba/workspace/icp_covs/3d-icp-cov/libpointmatcher/pointmatcher/PointMatcher.h:545:3: note: 
      'getCovariance' declared here
                virtual Matrix getCovariance() const;
                ^
1 error generated.
examples/CMakeFiles/icp_with_cov.dir/build.make:62: recipe for target 'examples/CMakeFiles/icp_with_cov.dir/icp_with_cov.cpp.o' failed
make[2]: *** [examples/CMakeFiles/icp_with_cov.dir/icp_with_cov.cpp.o] Error 1
CMakeFiles/Makefile2:572: recipe for target 'examples/CMakeFiles/icp_with_cov.dir/all' failed
make[1]: *** [examples/CMakeFiles/icp_with_cov.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ignaciotb** [comment]
Hi again, 
I'd also like to know if the base_config.yaml file is necessary to replicate your results, since it seems to be missing from you repo as well. 
Thanks again for your time

**Comment by mbrossar** [comment]
Mmmh, I see, some files are missing in the github repo. I have just updated all the repo and checked that it compiles. It should be ok now.

**Comment by ignaciotb** [comment]
Hi,
I've just pulled it and it seems to run fine.
There's just a warning for every data batch though which I wonder if I can safely ignore 
```
Unable to write the complete transformation file
```
